/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user by id
         * @description Own id, or any id for ADMIN / SUPER_ADMIN.
         */
        get: operations["getById"];
        /**
         * Update user by id
         * @description Own id, or any id for ADMIN / SUPER_ADMIN. Replaces first/last name, business name, business type and address; email, phone and password are not editable here.
         */
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get category
         * @description Fetch a single category by id. Anonymous callers only receive PUBLIC categories (HIDDEN → 404).
         */
        get: operations["getById_1"];
        /**
         * Update category
         * @description Replace an existing category.
         */
        put: operations["update_1"];
        post?: never;
        /**
         * Delete category
         * @description Delete a category that has no children and is not assigned to products.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rfqs/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject RFQ
         * @description Marks an RFQ as REJECTED (from NEW or UNDER_REVIEW). Optional reason is stored and shown to the customer.
         */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rfqs/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept RFQ
         * @description Marks an RFQ as ACCEPTED (from NEW or UNDER_REVIEW). Visible on the customer's account when they submitted while logged in.
         */
        post: operations["accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/rfqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit RFQ
         * @description Anonymous multipart form: product details, quantity, contact, location, optional photo. Creates an RFQ in NEW status. If a JWT is present, links the RFQ to that user for the account page.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/consultation-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request free consultation
         * @description Anonymous JSON form: name, company, business type, location, and phone/WhatsApp. Creates a consultation request in NEW status. If a JWT is present, links the request to that user via customerId.
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload image
         * @description Upload an image (thumbnail/listing/detail variants). Returns a media id to set on categories as iconMediaId, products, etc. Requires MinIO enabled.
         */
        post: operations["uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List categories
         * @description Paginated list with optional filters (slug, parentId, rootOnly, visibility, q). Anonymous callers only see PUBLIC categories; authenticated callers may filter any visibility.
         */
        get: operations["list"];
        put?: never;
        /**
         * Create category
         * @description Create a new catalog category.
         */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/initiate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start registration
         * @description Creates a pending account and sends an OTP to the chosen contact (email, or phone via SMS/WhatsApp). The account isn't usable until /otp/verify confirms the OTP.
         */
        post: operations["initiateRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset password
         * @description Sets a new password using the resetToken returned by a successful /otp/verify for the FORGET_PASSWORD purpose.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/forgot/send-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send the forgot-password OTP
         * @description Sends the OTP to the chosen verified channel for the account identified by the userToken from the initiate step.
         */
        post: operations["sendForgotPasswordOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/forgot/initiate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start forgot-password
         * @description Looks up the account by its verified email or phone number and returns the masked contact(s) it can send a reset OTP to.
         */
        post: operations["initiateForgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an OTP
         * @description Verifies an OTP for whichever purpose its token was issued for (registration, forgot-password, or alternate-contact verification) and returns that purpose's result — a JWT for a successful registration, a reset token for forgot-password, or a plain confirmation for alternate-contact verification.
         */
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend an OTP
         * @description Re-issues an OTP for the same purpose/channel as the given token; subject to the same cooldown as the original request.
         */
        post: operations["resendOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/oauth/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Social sign-up / sign-in
         * @description Exchange a verified OpenID Connect id_token from the given provider for a JWT. Creates the account on first sign-in, or links the provider identity to an existing account with the same verified email.
         */
        post: operations["socialLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with email/password and receive a JWT.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/contacts/verify/initiate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify my other contact
         * @description Sends an OTP to verify whichever contact (email or phone) on the authenticated account isn't verified yet.
         */
        post: operations["initiateContactVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rfqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List RFQs
         * @description Paginated RFQs. Filters: status, q (referenceNo / productName / contact). Default sort createdAt,desc. Attachments are loaded on the detail endpoint only.
         */
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rfqs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get RFQ
         * @description Admin RFQ detail including attachments and presigned media URLs.
         */
        get: operations["getById_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List public categories
         * @description Paginated PUBLIC categories. Lean payload (iconUrl thumbnail only). Cached in-memory; send Cache-Control for CDN/browser.
         */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public category by id */
        get: operations["getById_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/categories/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public category by slug */
        get: operations["getBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get media
         * @description Fetch media metadata and time-limited presigned URLs for each image variant.
         */
        get: operations["getById_4"];
        put?: never;
        post?: never;
        /**
         * Delete media
         * @description Delete an unreferenced media asset and its MinIO objects. Returns 409 if still attached. Abandoned uploads are also purged by orphan GC.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/rfqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my RFQs
         * @description Paginated RFQs submitted while authenticated as the current user. Empty when the user has none (anonymous submissions are not linked).
         */
        get: operations["listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/rfqs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my RFQ
         * @description Detail for an RFQ owned by the current user. Others → 404.
         */
        get: operations["getMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List consultation requests
         * @description Paginated leads from the free-consultation form. Filters: status, businessType, q (referenceNo / name / company / phone / location / businessType). Default sort createdAt,desc.
         */
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get consultation request
         * @description Admin consultation request detail.
         */
        get: operations["getById_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Public liveness probe.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PostalAddress: {
            recipientName?: string;
            phone?: string;
            line1?: string;
            line2?: string;
            city?: string;
            district?: string;
            postalCode?: string;
            /** @example BD */
            countryCode?: string;
        };
        /** @description Full replacement of the editable profile fields. Email, phone and password are changed through their own verified flows. */
        UserUpdateRequest: {
            firstName: string;
            lastName: string;
            businessName?: string;
            /** @example Importer */
            businessType?: string;
            address?: components["schemas"]["PostalAddress"];
        };
        /** @description Uniform API error envelope */
        ErrorResponse: {
            /** Format: date-time */
            timestamp?: string;
            /**
             * Format: int32
             * @example 400
             */
            status?: number;
            /** @example VALIDATION_FAILED */
            code?: string;
            message?: string;
            path?: string;
            traceId?: string;
            errors?: components["schemas"]["FieldErrorDTO"][];
        };
        FieldErrorDTO: {
            field?: string;
            code?: string;
            message?: string;
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            phoneNumber?: string;
            active?: boolean;
            emailVerified?: boolean;
            phoneVerified?: boolean;
            businessName?: string;
            businessType?: string;
            address?: components["schemas"]["PostalAddress"];
            roles?: ("SUPER_ADMIN" | "ADMIN" | "USER")[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description Create or update a catalog category */
        CategoryRequest: {
            /**
             * @description Localized display names (locale → text)
             * @example {
             *       "en": "Electronics",
             *       "bn": "ইলেকট্রনিক্স"
             *     }
             */
            name: {
                [key: string]: string;
            };
            /** @example electronics */
            slug: string;
            /**
             * Format: uuid
             * @description Parent category id; omit or null for a root category
             */
            parentId?: string;
            /**
             * Format: int32
             * @example 0
             */
            sortOrder?: number;
            /**
             * @example PUBLIC
             * @enum {string}
             */
            visibility: "PUBLIC" | "HIDDEN";
            /**
             * Format: uuid
             * @description Optional icon media asset id
             */
            iconMediaId?: string;
        };
        /** @description Catalog category. Nullables (parentId, iconMediaId, icon) are always serialized. */
        CategoryResponse: {
            /** Format: uuid */
            id?: string;
            name?: {
                [key: string]: string;
            };
            slug?: string;
            /** Format: uuid */
            parentId?: string;
            /** Format: int32 */
            sortOrder?: number;
            /** @enum {string} */
            visibility?: "PUBLIC" | "HIDDEN";
            /**
             * Format: uuid
             * @description Linked media asset id for the category icon, or null when unset
             */
            iconMediaId?: string | null;
            /** @description Resolved media payload with variant URLs when iconMediaId is set; otherwise null */
            icon?: components["schemas"]["MediaResponse"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            version?: number;
        };
        /** @description Uploaded media asset with optional presigned variant URLs */
        MediaResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            kind?: "IMAGE" | "DOCUMENT" | "VIDEO" | "OTHER";
            mimeType?: string;
            /** Format: int64 */
            sizeBytes?: number;
            altText?: string;
            variants?: {
                [key: string]: string;
            };
            urls?: {
                [key: string]: string;
            };
            /** Format: date-time */
            urlsExpireAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description Optional reason when rejecting an RFQ */
        RfqRejectRequest: {
            /** @example Unable to source this product currently */
            reason?: string;
        };
        /** @description Admin RFQ detail */
        Rfq: {
            /** Format: uuid */
            id?: string;
            referenceNo?: string;
            /** Format: uuid */
            customerId?: string;
            /** @enum {string} */
            sourceType?: "GENERAL" | "PRODUCT" | "FACTORY";
            /** Format: uuid */
            sourceId?: string;
            productName?: string;
            description?: string;
            /** Format: int32 */
            quantity?: number;
            unit?: string;
            specifications?: string;
            destinationCountry?: string;
            deliveryRequirements?: string;
            contactName?: string;
            contactEmail?: string;
            contactPhone?: string;
            contactCompany?: string;
            /** @enum {string} */
            status?: "NEW" | "UNDER_REVIEW" | "QUOTATION_PREPARED" | "QUOTATION_SENT" | "ACCEPTED" | "REJECTED" | "COMPLETED";
            internalNotes?: string;
            attachments?: components["schemas"]["RfqAttachment"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            version?: number;
        };
        /** @description RFQ product photo attachment */
        RfqAttachment: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            mediaId?: string;
            originalName?: string;
            thumbnailUrl?: string;
            media?: components["schemas"]["MediaResponse"];
        };
        /** @description Public request-for-quote form fields */
        RfqCreateRequest: {
            /**
             * @description Product name & details
             * @example Bluetooth speaker, black, 20W
             */
            productName: string;
            /** @description Optional extra product details */
            description?: string;
            /**
             * Format: int32
             * @example 100
             */
            quantity: number;
            /**
             * @description Quantity unit label
             * @example pcs
             */
            unit?: string;
            /** @example Ajoy Deb Nath */
            contactName: string;
            /**
             * @description Optional business / company name
             * @example Global Grid Ltd
             */
            businessName?: string;
            /**
             * @description Dialing code for phone
             * @example +880
             */
            phoneCountryCode?: string;
            /**
             * @description National number or full E.164 phone / WhatsApp
             * @example 1712345678
             */
            phone: string;
            /**
             * @description Delivery destination (city / region)
             * @example Dhaka
             */
            location: string;
        };
        /** @description Storefront RFQ submit confirmation */
        RfqPublic: {
            /** Format: uuid */
            id?: string;
            referenceNo?: string;
            /** @enum {string} */
            status?: "NEW" | "UNDER_REVIEW" | "QUOTATION_PREPARED" | "QUOTATION_SENT" | "ACCEPTED" | "REJECTED" | "COMPLETED";
            productName?: string;
            description?: string;
            /** Format: int32 */
            quantity?: number;
            unit?: string;
            contactName?: string;
            businessName?: string;
            phone?: string;
            location?: string;
            destinationCountry?: string;
            /**
             * Format: uuid
             * @description Set when the submitter was logged in; null for anonymous RFQs
             */
            customerId?: string | null;
            /** @description Presigned thumbnail URL of the uploaded photo, or null */
            photoUrl?: string | null;
            /** @description Admin note when rejected (or other status note); otherwise null */
            statusNote?: string | null;
        };
        /** @description Public free-consultation form fields */
        ConsultationRequestCreate: {
            /**
             * @description Full name
             * @example Tareq Rahman
             */
            name: string;
            /**
             * @description Business / company name
             * @example Apex Global Trade
             */
            companyName: string;
            /**
             * @description Business type from the storefront dropdown
             * @example Manufacturer / Exporter
             */
            businessType: string;
            /**
             * @description Business location (city / country / port)
             * @example Dhaka, Bangladesh / Global Port
             */
            location: string;
            /**
             * @description Phone or WhatsApp number (national digits or full E.164)
             * @example +880 1700-000000
             */
            contactNumber: string;
        };
        /** @description Storefront consultation submit confirmation */
        ConsultationRequestPublic: {
            /** Format: uuid */
            id?: string;
            referenceNo?: string;
            /** @enum {string} */
            status?: "NEW" | "CONTACTED" | "CLOSED";
            name?: string;
            companyName?: string;
            businessType?: string;
            location?: string;
            contactNumber?: string;
            /**
             * Format: uuid
             * @description Set when the submitter was logged in; null for anonymous requests
             */
            customerId?: string | null;
        };
        /** @description Registration payload — provide email and/or phone number, but only the contact matching otpChannel is verified by this call. */
        RegisterRequest: {
            firstName: string;
            lastName: string;
            /** @example trader@example.com */
            email?: string;
            /** @example +8801XXXXXXXXX */
            phoneNumber?: string;
            password: string;
            confirmPassword: string;
            /**
             * @description Which contact to verify now — EMAIL sends to `email`, SMS/WHATSAPP send to `phoneNumber`.
             * @enum {string}
             */
            otpChannel: "EMAIL" | "SMS" | "PUSH" | "WHATSAPP" | "IN_APP";
        };
        MessageResponse: {
            message?: string;
            additionalData?: {
                [key: string]: unknown;
            };
        };
        ResetPasswordRequest: {
            resetToken: string;
            newPassword: string;
            confirmNewPassword: string;
        };
        ForgotPasswordSendOtpRequest: {
            userToken: string;
            /** @enum {string} */
            otpChannel: "EMAIL" | "SMS" | "PUSH" | "WHATSAPP" | "IN_APP";
        };
        ForgotPasswordInitiateRequest: {
            /** @description The verified email or phone number on the account. */
            username: string;
        };
        MaskedContactDetails: {
            /**
             * @description EMAIL or PHONE
             * @example EMAIL
             */
            type?: string;
            /** @example t***@example.com */
            maskedValue?: string;
            /** @description Short-lived token identifying this forgot-password session — pass it to /password/forgot/send-otp. */
            userToken?: string;
        };
        VerifyOtpRequest: {
            /** @description Optional sanity check against the account the token belongs to. */
            email?: string;
            phoneNumber?: string;
            token: string;
            otp: string;
        };
        ResendOtpRequest: {
            token: string;
        };
        /** @description OIDC id_token issued by the provider's sign-in SDK */
        SocialLoginRequest: {
            /** @description The provider's signed id_token (JWT) */
            credential: string;
        };
        /** @description Authenticated user and JWT */
        LoginResponse: {
            /** Format: uuid */
            id?: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            roles?: string[];
            /** @description JWT access token — send as Authorization: Bearer <token> */
            token?: string;
        };
        /** @description Email or phone number + password login payload */
        LoginRequest: {
            /**
             * @description The account's verified email or phone number
             * @example ajoy.debnath@globalgrid.com
             */
            email: string;
            /** @example 123456 */
            password: string;
        };
        ContactVerifyInitiateRequest: {
            /**
             * @description EMAIL to verify the account's email, SMS/WHATSAPP to verify its phone number.
             * @enum {string}
             */
            otpChannel: "EMAIL" | "SMS" | "PUSH" | "WHATSAPP" | "IN_APP";
        };
        PageResponseRfq: {
            content?: components["schemas"]["Rfq"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            sort?: string[];
        };
        /** @description Storefront-optimized category */
        CategoryPublic: {
            /** Format: uuid */
            id?: string;
            name?: {
                [key: string]: string;
            };
            slug?: string;
            /** Format: uuid */
            parentId?: string;
            /** Format: int32 */
            sortOrder?: number;
            /** @description Presigned thumbnail URL, or null when no iconMediaId */
            iconUrl?: string | null;
        };
        PageResponseCategoryPublic: {
            content?: components["schemas"]["CategoryPublic"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            sort?: string[];
        };
        PageResponseRfqPublic: {
            content?: components["schemas"]["RfqPublic"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            sort?: string[];
        };
        /** @description Admin consultation request detail */
        ConsultationRequest: {
            /** Format: uuid */
            id?: string;
            referenceNo?: string;
            /** Format: uuid */
            customerId?: string;
            name?: string;
            companyName?: string;
            businessType?: string;
            location?: string;
            contactNumber?: string;
            /** @enum {string} */
            status?: "NEW" | "CONTACTED" | "CLOSED";
            internalNotes?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            version?: number;
        };
        PageResponseConsultationRequest: {
            content?: components["schemas"]["ConsultationRequest"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            sort?: string[];
        };
        PageResponseCategoryResponse: {
            content?: components["schemas"]["CategoryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            sort?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Not your profile */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not your profile */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Slug conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Has children or product references */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RfqRejectRequest"];
            };
        };
        responses: {
            /** @description Rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Rfq"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid status transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Rfq"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid status transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["RfqCreateRequest"];
            };
        };
        responses: {
            /** @description RFQ created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RfqPublic"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Photo upload failed (storage) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsultationRequestCreate"];
            };
        };
        responses: {
            /** @description Consultation request created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConsultationRequestPublic"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    uploadImage: {
        parameters: {
            query?: {
                folder?: string;
                altText?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Uploaded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MediaResponse"];
                };
            };
            /** @description Missing/invalid file */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Storage unavailable / upload failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string[];
                slug?: string;
                parentId?: string;
                rootOnly?: boolean;
                visibility?: "PUBLIC" | "HIDDEN";
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseCategoryResponse"];
                };
            };
            /** @description Invalid page/sort/filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Slug conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    initiateRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    sendForgotPasswordOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordSendOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    initiateForgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordInitiateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MaskedContactDetails"][];
                };
            };
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    resendOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    socialLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Social provider
                 * @example google
                 */
                provider: "GOOGLE";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialLoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Unknown/unconfigured provider or validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid, expired, or unverified token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    initiateContactVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactVerifyInitiateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string[];
                status?: "NEW" | "UNDER_REVIEW" | "QUOTATION_PREPARED" | "QUOTATION_SENT" | "ACCEPTED" | "REJECTED" | "COMPLETED";
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of RFQs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseRfq"];
                };
            };
            /** @description Invalid page/sort/filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Rfq"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string[];
                slug?: string;
                parentId?: string;
                rootOnly?: boolean;
                visibility?: "PUBLIC" | "HIDDEN";
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of public categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseCategoryPublic"];
                };
            };
            /** @description Invalid page/sort/filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryPublic"];
                };
            };
            /** @description Not found / not PUBLIC */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryPublic"];
                };
            };
            /** @description Not found / not PUBLIC */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getById_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MediaResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Still referenced */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listMine: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of the caller's RFQs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseRfqPublic"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RfqPublic"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found / not owned */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort?: string[];
                status?: "NEW" | "CONTACTED" | "CLOSED";
                businessType?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of consultation requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseConsultationRequest"];
                };
            };
            /** @description Invalid page/sort/filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getById_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConsultationRequest"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
}
