/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCategoriesIndexRouteImport } from './routes/_app/categories/index'
import { Route as AppConsultationsIndexRouteImport } from './routes/_app/consultations/index'
import { Route as AppRfqsIndexRouteImport } from './routes/_app/rfqs/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultationsIndexRoute = AppConsultationsIndexRouteImport.update({
  id: '/consultations/',
  path: '/consultations/',
  getParentRoute: () => AppRoute,
} as any)
const AppRfqsIndexRoute = AppRfqsIndexRouteImport.update({
  id: '/rfqs/',
  path: '/rfqs/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/categories/': typeof AppCategoriesIndexRoute
  '/consultations/': typeof AppConsultationsIndexRoute
  '/rfqs/': typeof AppRfqsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/consultations': typeof AppConsultationsIndexRoute
  '/rfqs': typeof AppRfqsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
  '/_app/consultations/': typeof AppConsultationsIndexRoute
  '/_app/rfqs/': typeof AppRfqsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/categories/' | '/consultations/' | '/rfqs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/categories' | '/consultations' | '/rfqs'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/categories/'
    | '/_app/consultations/'
    | '/_app/rfqs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultations/': {
      id: '/_app/consultations/'
      path: '/consultations'
      fullPath: '/consultations/'
      preLoaderRoute: typeof AppConsultationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rfqs/': {
      id: '/_app/rfqs/'
      path: '/rfqs'
      fullPath: '/rfqs/'
      preLoaderRoute: typeof AppRfqsIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppConsultationsIndexRoute: typeof AppConsultationsIndexRoute
  AppRfqsIndexRoute: typeof AppRfqsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppConsultationsIndexRoute: AppConsultationsIndexRoute,
  AppRfqsIndexRoute: AppRfqsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
